### ISSUE TITLE
NoMoWanderer causing server crashes with ATM9 v0.0.56 

### ISSUE THREAD

**Issue by SpaghettiooH** [J-Dill/NoMoWanderer#16]
Redirected here from the ATM9 team on their discord. 

Online Log:
https://mclo.gs/Pjq0J8J

Original Crash Log:
[crash-2023-08-23_11.41.50-server.txt](https://github.com/J-Dill/NoMoWanderer/files/12418833/crash-2023-08-23_11.41.50-server.txt)

**Comment by J-Dill** [comment]
@SpaghettiooH I am still looking at this; rest assured.

**Comment by J-Dill** [comment]
Still working on this; to fix this issue will take a rework of the mod from the ground-up so this may take a little while.

**Comment by TigerWalts** [comment]
I am experiencing this problem with Chosen's Modded Adventure modpack.

The main server thread hangs while NoMoWanderer is handling entity spawns and checking for block entities. The hang happens while it is tying to build a collection of chunks around the event location.

I suspect that this is resulting in a deadlock on access to the chunk cache.

---

A possible fix may be to change the `checkBlockEntities` method so that it cancels the spawn event and then runs its checks in a task where access to the chunk cache can be guaranteed. It can then spawn the entity if the conditions permit.

**Comment by J-Dill** [comment]
This should be all good to go now in the latest 1.20.1 version of NoMoWanderer: 1.6.1
