### ISSUE TITLE
Suggestion: a sign that designates where a trader can spawn 

### ISSUE THREAD

**Issue by Nightcaste** [J-Dill/NoMoWanderer#8]
I'm having a hard time putting this into words. I would like to suggest a second sign that, if a trader would spawn, forces them to show up within a configurable distance from the sign, and stay within that distance.

The idea being you can put the sign somewhere that it would be ok for them to show up, and they stay over there instead of spawning anywhere and running all over your base, or being up in your face all the time.

**Comment by J-Dill** [comment]
Yeah I understand what you are asking for; a new block could be made that when a trader spawns the game will search for this new block somewhere near. If it finds one, it will make the trader spawn on/near that block instead of the original spot.

I don't think I will be able to implement the part about keeping them near the block, as that gets into changing the path finding of vanilla mobs and that gets pretty complicated quickly as I have found out previously :)

Instead you could just put fencing around the block or something similar to keep them around it yourself.

Sound like a good compromise? :)

**Comment by Nightcaste** [comment]
I just want the dude out of my face and out of my farms.  If I can contain
them to a particular area, that would be great

**Comment by J-Dill** [comment]
Fair enough, I'll start looking into implementing something like this then!

**Comment by Nightcaste** [comment]
Thank you

**Comment by J-Dill** [comment]
And thank you, I always appreciate new ideas for expanding the usefulness of my mods 😃

**Comment by J-Dill** [comment]
@Nightcaste A new version of the mod has just been released that includes a new block: the Trader Rug! When placed down, it will direct any nearby entities that try to spawn (that are in the config) to spawn on that rug if they are in the radius.

Let me know what you think!

**Comment by SheReyy** [comment]
> @Nightcaste A new version of the mod has just been released that includes a new block: the Trader Rug! When placed down, it will direct any nearby entities that try to spawn (that are in the config) to spawn on that rug if they are in the radius.
> 
> Let me know what you think!

I presume the Rug is a 1.18/1.19 feature only right? I'm in 1.16.5 and there's no rug. Any change it can be backported?
Edit: Actually, all the Rug does is to direct the configured entities to spawn at its location? Doesn't it also boost the spawn chance? I was looking for a way to get the wandering trader faster in the game.
